menu:
    Blog: /
    Archive: /archives/
    About: /cv/

favicon: /favicon_tree.png
logo: /favicon_tree.png

# Comment
disqus: mikemadison
duoshuo:

# Analytics
# google-analytics:
ga: ~

# Copyright Infomation
startyear: 2016
